version: '3.7'

services:
  web:
    build: ./services/web
    command: python -m ptvsd --host 0.0.0.0 --port 5678 --multiprocess manage.py run --no-debugger --no-reload -h 0.0.0.0
    #command: python -m ptvsd --host 0.0.0.0 --port 5678 --wait --multiprocess -m flask run --no-debugger --no-reload
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
      - 5678:5678
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tcc
      - POSTGRES_PASSWORD=tcc
      - POSTGRES_DB=tcc

volumes:
  postgres_data:
