# Generated by Django 2.2.9 on 2020-01-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='last_expiration',
            field=models.DateTimeField(null=True),
        ),
    ]
